### ISSUE TITLE
Java version compatibility notice

### ISSUE THREAD

**Issue by ungikim** [uyu423/winter-is-leaving-and-Spring-is-coming#1]
Spring Framework 4 - Java 8 까지
Spring Framework 5 - Java 9 지원 시작
3rd Party Library 가 Java 9 호환성이 떨어질 수 있음.

**Comment by uyu423** [comment]
센빠이도 스프링에 관심이 많으시군요..

**Comment by ungikim** [comment]
작년에도 썼는데...
